server.port: 8081
spring.cache:
  type: redis
  redis.time-to-live: 1m

management.endpoints.web.exposure.include: "*"

management.metrics:
    export:
      datadog:
        api-key: ${DATADOG_API_KEY}
        step: 10s
    distribution:
      percentiles[http.server.requests]: 0.50, 0.75, 0.95, 0.99
      percentiles-histogram[http.server.requests]: true